- name: Ansible Playbook to Install and Setup Zookeeper on Ubuntu
  hosts: zookeeper-nodes
  remote_user: ubuntu
  become: yes  
  tasks:       
    - name: Print the gateway for each host when defined    
      ansible.builtin.debug:
        msg: System {{ ansible_play_hosts_all }} 
    
  