- name: Install Java
  hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Install Java
      apt: name=openjdk-8-jdk update_cache=yes state=latest

- name: Ansible Playbook to Install and Setup Zookeeper on Ubuntu
  hosts: zookeeper-nodes
  remote_user: ubuntu
  become: yes
  roles:
    - role: sleighzy.zookeeper
      vars:
        zookeeper_servers_use_inventory_hostname: true
        zookeeper_servers:
        - "{{ansible_play_hosts_all[0]}}"
        - "{{ansible_play_hosts_all[1]}}"        

- name: Ansible Playbook to Install and Setup Apache on Ubuntu
  hosts: kafka
  remote_user: ubuntu
  become: yes
  roles:    
    - role: sleighzy.kafka
      vars:
        # FIXME - update the JVM heap for your setup
        kafka_java_heap: "-Xms256m -Xmx256m"
        kafka_advertised_listeners: ["PLAINTEXT://{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}:9092"]
        kafka_listeners: 
          - "PLAINTEXT://{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}:9092"
        kafka_zookeeper_connect: "{{ansible_play_hosts_all[0]}}:2181,{{ansible_play_hosts_all[1]}}:2181"
                